version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog

  api:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./src:/app/src
    command: ['yarn', 'dev']
    links:
      - postgres:db
    ports:
      - "8080:8080"
    restart: always
